### ISSUE TITLE
PIF documentation 404

### ISSUE THREAD

**Issue by sinistral** [CitrineInformatics/api-documentation#7]
The URL `https://www.citrine.io/pif` is used at various points in our public documentation, but does not exist.

* https://citrineinformatics.github.io/api-documentation/
* http://citrineinformatics.github.io/pif-documentation/schema_definition/system/System.html?search=pigquery&start=0

**Comment by kjaym** [comment]
@sinistral https://www.citrine.io/pif redirects to the proper page - http://citrineinformatics.github.io/pif-documentation. Is that not working for you?

**Comment by maxhutch** [comment]
It didn't seem to work for me at at least one point this morning.

**Comment by sinistral** [comment]
That's odd.  It's working now, but it was failing consistently when I cut the ticket.  Has the site been republished recently?

If it's working now, then there's little point in keeping the ticket open.

**Comment by kjaym** [comment]
I haven't touched anything in weeks. Maybe just an issue with our host for citrine.io? Is there anything that you want to do, or should we just close this?

**Comment by sinistral** [comment]
If 404s for the documentation are surfaced in the availability reports so that we can tell if this is happening to users, then there's nothing else that I would want to do now and we can close.

**Comment by kjaym** [comment]
👍
